repositories {
    mavenLocal()

    //REI, Cloth, Architectury
    maven { url = "https://maven.shedaniel.me" }

    //Curse
    maven {
        url = "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }

    //Modrinth
    maven { url = "https://api.modrinth.com/maven" }

    //LibGUI
    //maven {
    //    name = "AlexIIL"
    //    url = "https://staging.alexiil.uk/maven/"
    //}

    //PAL
    maven {
        name = 'Ladysnake Mods'
        url = 'https://maven.ladysnake.org/releases'
        content {
            includeGroup 'io.github.ladysnake'
            includeGroupByRegex 'io\\.github\\.onyxstudios.*'
        }
    }

    //Terraformer
    maven {
        name = 'TerraformersMC'
        url = 'https://maven.terraformersmc.com/'
    }

    //Minecraft Forge
    maven { url = 'https://maven.minecraftforge.net/' }

    //kyrptonaught
    maven { url = "https://maven.kyrptonaught.dev" }

    //JEI
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    //The Mentor
    maven { url = 'https://repo.repsy.io/mvn/thementor/jilibs' }
}